### ISSUE TITLE
你好，有小demo吗？

### ISSUE THREAD

**Issue by yxzfx** [chenxianqi/flutter_mimc#4]

**Comment by chenxianqi** [comment]
clone 下来填写相应的appid就可以跑

**Comment by yxzfx** [comment]
好的，我跑一下，谢谢

**Comment by yxzfx** [comment]
> clone 下来填写相应的appid就可以跑

好的，主要是我直接看您的那个说明例子集成到自己的项目里了，左移猛地有点蒙，我先跑一下，谢谢

**Comment by yxzfx** [comment]
> clone 下来填写相应的appid就可以跑

好的，我直接看的您的那个例子，想集成到自己的项目里，所有有点蒙，我先跑一下，谢谢您

**Comment by chenxianqi** [comment]
好的，使用过程有任何问题，欢迎提问
