### ISSUE TITLE
支持离线消息吗？

### ISSUE THREAD

**Issue by MuZiLee** [chenxianqi/flutter_mimc#5]
flutter 的IM很少啊。
融云免费版只能注册100个账号。网易云信是个极大的坑，用过都怕。
腾讯云又很麻烦。

现在想问问关于消息推送的问题：
1：当App退出后是否能够接收推送消息。
2：离线消息类型分几种，MIMC有没有做消息保存？单个离线用户消息最多保存多少条，保存多久？

**Comment by chenxianqi** [comment]
这些问题，请看mimc的文档，这个插件只是移植，还请您移步哈

**Comment by chenxianqi** [comment]
Mimc不负责你的app消息推送，推送部分你应该自己解决，mimc有消息回调，目前mimc应该是免费使用

**Comment by chenxianqi** [comment]
该issue先关闭了
