### ISSUE TITLE
【账号密钥】【云服务密钥】

### ISSUE THREAD

**Issue by MuZiLee** [chenxianqi/flutter_mimc#6]
在小米开放平台里，一个是创建应用，然后，只有一个appid ，而没有 appKey。
![image](https://user-images.githubusercontent.com/7467318/68134663-6bf88000-ff5d-11e9-9d4d-9816d4a079a4.png)
然后我去到密钥中心创建了一个账号密钥。
![image](https://user-images.githubusercontent.com/7467318/68134756-8894b800-ff5d-11e9-9705-e9c8a9226d81.png)
但他下面还有个云服务。我试了下创建，结果是生成的东西是一样的。
![image](https://user-images.githubusercontent.com/7467318/68134877-b974ed00-ff5d-11e9-8cc4-08e345f6b2c8.png)
这默认两可很费解啊。这怎appkey应该选哪个？

**Comment by chenxianqi** [comment]
这个你最好看一下mimc的文档哦

**Comment by chenxianqi** [comment]
该issue先关闭了
